### ISSUE TITLE
[BUG] Font size for new properties 

### ISSUE THREAD

**Issue by chrisk-7777** [crashmoney/obsidian-typewriter#36]
## Describe the bug

Awesome theme! 

Obsidian recently added a new feature called "properties". 

This theme renders the font for these smaller than other themes, making it a tad difficult to read. 

## To Reproduce

1. Enable Typewrite theme
2. Add a new property and populate (this can be done with `cmd + ;`)
3. Observe smaller size

## Information
 - OS: MacOS - 13.5.2 (22G91)

![CleanShot 2023-11-20 at 19 58 15](https://github.com/crashmoney/obsidian-typewriter/assets/55621012/8b671f6f-c52f-4703-a935-769e4552390d)

**Typewrite font size 0.688em**

![CleanShot 2023-11-20 at 19 59 50@2x](https://github.com/crashmoney/obsidian-typewriter/assets/55621012/22fb70f9-07ee-4498-b1b3-8a6b305818ff)

**Default font size 0.875em**

![CleanShot 2023-11-20 at 19 59 35@2x](https://github.com/crashmoney/obsidian-typewriter/assets/55621012/2132f2da-6fbb-4be6-b7d4-e55244d3fddb)

I'm happy to raise a PR, but digging in to the theme.css I couldn't find anything related to metadata, so I'm not 100% where the font size is coming in for this theme.

**Comment by crashmoney** [comment]
Hey @chrisk-7777, thanks so much for using the theme and the detailed bug report!

The issue turned out to just be Typewriter not having the `--metadata-input-font-size` variable available. I've since linked it to the `--font-small` variable, which was a design decision on my part to have the metadata legible but not overtaking the actual text. It's quite close to the default size of 0.875em, actually 😄

Hope this helps!

**Comment by chrisk-7777** [comment]
Fantastic thank you!
