### ISSUE TITLE
[BUG] Heading size inconsistencies in live preview

### ISSUE THREAD

**Issue by ryadaj** [crashmoney/obsidian-typewriter#7]
I love this theme! It has been my main theme for a while now. Thank you so much.

## Describe the bug
Perhaps it is intentional, but Heading level 4 appears bigger than H3 in Live Preview mode. 

![Screen Shot 2022-01-25 at 12 58 30](https://user-images.githubusercontent.com/82765301/151033253-f28179fd-bd38-4a64-afbe-fbd5dcefd50c.png)

## To Reproduce
1. Create a note
2. Create headings 1–6
3. Compare sizes

## Information
 - OS: Mac OS X (most recent release)

## Suggestions/Workarounds
I am not savvy enough to know :)
![Screen Shot 2022-01-25 at 12 58 30](https://user-images.githubusercontent.com/82765301/151033253-f28179fd-bd38-4a64-afbe-fbd5dcefd50c.png)

**Comment by bdirinck** [comment]
On line 863 till 864 the following is written:

.is-live-preview .HyperMD-header-3,
.is-live-preview .cm-header-3 {
  font-size: var(--h4-live-preview);


Should be 4 instead of 3:

.is-live-preview .HyperMD-header-4,
.is-live-preview .cm-header-4 {
  font-size: var(--h4-live-preview);


<img width="701" alt="2022-02-24-screenshot" src="https://user-images.githubusercontent.com/66790261/155611371-680aa679-f234-4385-9cec-9ce80d2592b6.png">
-

**Comment by crashmoney** [comment]
I just pushed an update that fixes this. Could you try updating the theme and letting me know whether it works? Thanks!
